name: Build and Deploy to Heroku
on:
  push:
    branches:
      - develop
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Actions checkout
        uses: actions/checkout@v3
      - name: Entry to server
        run: cd ./src/server
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_app_name: "server-world-cup-information"
          heroku_email: "adoa2705@gmail.com"
          appdir: './src/server'
    
